FROM centos:8

LABEL description="build antdb regress env"

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN sed -e 's|^mirrorlist=|#mirrorlist=|g' \
         -e 's|^#baseurl=http://mirror.centos.org/$contentdir|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos|g' \
         -i.bak \
         /etc/yum.repos.d/CentOS-*.repo
RUN yum makecache
RUN yum update -y

RUN yum install -y gcc flex bison make perl-ExtUtils-Embed python3 python3-devel readline-devel zlib-devel pam-devel libxml2 libxml2-devel libxslt libxslt-devel openldap openldap-devel wget git perl perl-devel sudo
RUN dnf -y --enablerepo=powertools install perl-IPC-Run perl-Capture-Tiny perl-DateTime perl-namespace-autoclean

WORKDIR /home
RUN git clone --depth=1 https://ghproxy.com/https://github.com/linux-test-project/lcov -b v1.14 /home/lcov
WORKDIR /home/lcov
RUN make install
RUN genhtml -V

WORKDIR /home
RUN wget https://libssh2.org/download/libssh2-1.11.0.tar.gz
RUN tar -zxf libssh2-1.11.0.tar.gz
WORKDIR /home/libssh2-1.11.0
RUN ./configure
RUN make install
WORKDIR /home
RUN rm -rf /home/lcov
RUN rm libssh2-1.11.0.tar.gz
RUN rm -rf /home/libssh2-1.11.0

RUN useradd -ms /bin/bash centos

RUN echo 'centos ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV LANG en_US.utf8

USER centos

# RUN pip3 install --user gcovr -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN echo "export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH" >> $HOME/.bashrc


#ENTRYPOINT ["su", "centos"]


# https://pkgs.org/





cd /home/build
/home/AntDB/configure --prefix=/home/app \
--with-segsize=4 \
--with-wal-blocksize=64 \
--enable-grammar-oracle \
--with-perl \
--with-python \
--with-pam \
--with-ldap \
--with-libxml \
--with-libxslt \
--enable-thread-safety \
--enable-tap-tests \
--enable-coverage \
--enable-debug \
--disable-cassert \
--enable-depend  && \
make -j16 && make install && \
cd contrib && make -j16 && make install

RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys && \
    echo -e "StrictHostKeyChecking no \nUserKnownHostsFile /dev/null" >> ~/.ssh/config

ARG ESGYNDB_DOWNLOAD_LINK
ARG ESGYNDB_VERSION

# get esgyn build
RUN echo "10.1.40.25 downloads.esgyn.local" >> /etc/hosts && \
    wget ${ESGYNDB_DOWNLOAD_LINK} && \
    mkdir -p ${TRAF_DIR} && chmod 700 ${TRAF_DIR} && \
    mkdir -p ${TRAF_HOME} && mkdir -p ${TRAF_CFG_DIR} && mkdir -p ${TRAF_DIR}/sqllogs && \
    tar xf /esgynDB_server-${ESGYNDB_VERSION}-RH7-x86_64.tar.gz -C ${TRAF_HOME} && chmod 700 ${TRAF_HOME} && \
    rm -rf /esgynDB_server-${ESGYNDB_VERSION}-RH7-x86_64.tar.gz

# env_setup
RUN sed -i "s!export TAR_DOWNLOAD_ROOT=.*!export TAR_DOWNLOAD_ROOT=${TRAF_DIR}/sqllogs!g" ${TRAF_HOME}/sqenvcom.sh && \
    sed -i "s!export CACERTS_DIR=.*!export CACERTS_DIR=${TRAF_DIR}/cacerts!g" ${TRAF_HOME}/sqenvcom.sh && \
    sed -i "s!sqllogdir=.*!sqllogdir=${TRAF_DIR}/sqllogs!g" ${TRAF_HOME}/sql/scripts/genms && \
    sed -i "s!cacertsdir=.*!cacertsdir=${TRAF_DIR}/cacerts!g" ${TRAF_HOME}/sql/scripts/genms && \
    cp -f ${TRAF_HOME}/sysinstall/home/trafodion/.bashrc /root/.bashrc

# copy_file
RUN mv /opt/trafodion_config ${TRAF_CFG_DIR}/trafodion_config && \
    mv /opt/config.xml ${TRAF_CONF}/dbmgr/config.xml && \
    mv /opt/dcs-site-cloud.xml ${TRAF_CONF}/dcs/dcs-site-cloud.xml && \
    mv /opt/dcs-site.xml ${TRAF_CONF}/dcs/dcs-site.xml && \
    mv /opt/rest-site.xml ${TRAF_CONF}/rest/rest-site.xml && \
    cp ${TRAF_HOME}/mgblty/opentsdb/etc/opentsdb/opentsdb.conf ${TRAF_CONF}/mgblty/opentsdb/ && \
    cp ${TRAF_HOME}/mgblty/bosun/conf/bosun.conf ${TRAF_CONF}/mgblty/bosun/

# hbase_trx
RUN cp ${TRAF_HOME}/export/lib/trafodion-utility-* ${HBASE_LIB} && chmod a+r ${HBASE_LIB}/trafodion-utility-* && \
    cp ${TRAF_HOME}/export/lib/hbase-trx-apache1_1-${ESGYNDB_VERSION}.jar ${HBASE_LIB} && chmod a+r ${HBASE_LIB}/hbase-trx-*

# traf_config
RUN echo -e "begin node\nnode-id=0;node-name=localhost;cores=0-1;processors=1;roles=connection,aggregation,storage\nend node\n\nbegin overflow\nhdd $TRAF_VAR\nend overflow\n" > $TRAF_CONF/sqconfig && \
    sed -i 's/tsdbHost = .*/tsdbHost = localhost:5242/g' ${TRAF_CONF}/mgblty/bosun/bosun.conf && \
    sed -i 's/tsd.network.port = .*/tsd.network.port = 5242/g' ${TRAF_CONF}/mgblty/opentsdb/opentsdb.conf && \
    sed -i "s/tsd.storage.hbase.zk_quorum = .*/tsd.storage.hbase.zk_quorum = ${HOSTNAME}/g" ${TRAF_CONF}/mgblty/opentsdb/opentsdb.conf && \
    if [ -f /etc/timezone ]; then TIMEZONE=`cat /etc/timezone`;elif [ -h /etc/localtime ]; then TIMEZONE=`readlink /etc/localtime | sed "/posix/d;s/.*\/usr\/share\/zoneinfo\///"`; \
    else checksum=`md5sum /etc/localtime | cut -d' ' -f1`;TIMEZONE=`find /usr/share/zoneinfo/ -maxdepth 1 -type f -exec md5sum {} \; | grep "^$checksum" | \
    sed "/posix/d;s/.*\/usr\/share\/zoneinfo\///"`;fi && \
    sed -i "s#\"timeZoneName\".*#\"timeZoneName\">$TIMEZONE</entry>#g" ${TRAF_CONF}/dbmgr/config.xml && \
    sed -i "s/tsd.core.timezone = .*/tsd.core.timezone = $TIMEZONE/g" ${TRAF_CONF}/mgblty/opentsdb/opentsdb.conf && \
    sed -i '$a\tsd.storage.hbase.data_table=TRAF_RSRVD_7:tsdb\ntsd.storage.hbase.tree_table=TRAF_RSRVD_7:tsdb-tree\ntsd.storage.hbase.uid_table=TRAF_RSRVD_7:tsdb-uid\ntsd.storage.hbase.meta_table=TRAF_RSRVD_7:tsdb-meta' ${TRAF_CONF}/mgblty/opentsdb/opentsdb.conf && \
    sed -i "s/TSDPORT=.*/TSDPORT=5242/g" ${TRAF_HOME}/mgblty/tcollector/startstop && \
    echo -e "${HOSTNAME}" > ${TRAF_CONF}/dcs/masters && echo -e "${HOSTNAME} 4" > ${TRAF_CONF}/dcs/servers

CMD ["/opt/start.sh"]

EXPOSE 4205



https://blog.csdn.net/weixin_43252521/article/details/124409151

cd /etc/yum.repos.d/

sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*


sed -e 's|^mirrorlist=|#mirrorlist=|g' \
         -e 's|^#baseurl=http://mirror.centos.org/$contentdir|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos|g' \
         -i.bak \
         /etc/yum.repos.d/CentOS-*.repo

yum makecache

yum update -y

yum -y install vim
yum install initscripts -y
yum install openssh-server -y
yum install -y epel-release
yum install -y readline-devel redhat-lsb
yum install -y alsa-lib-devel ant apr apr-devel apr-util apr-util-devel automake
yum install -y bison boost-devel byacc
yum install -y cmake
yum install -y device-mapper-multipath 
yum install -y flex htop
yum install -y gcc-c++ gd git glibc-devel  gzip
yum install -y libaio-devel libcurl-devel libevent-devel  libibumad-devel libiodbc
yum install -y libiodbc-devel librdmacm-devel libtool libuuid-devel libX11-devel
yum install -y libXau-devel libXext-devel libxml++ libxml2-devel
yum install -y log4cxx log4cxx-devel
yum install -y lzo-devel lzo-minilzo lzop
yum install -y ncurses-devel ncurses-libs net-snmp-devel net-snmp-perl
yum install -y openldap-clients openldap-devel openmotif openssl-devel 
yum install -y snappy sqlite-devel protobuf-compiler
yum install -y tog-pegasus libcgroup-tools.x86_64 libcgroup
yum install -y unixODBC unixODBC-devel unzip wget xerces-c-devel xinetd zeromq zeromq-devel zlib-devel go
yum install -y gdb sudo net-tools vim perl-DBD-SQLite perl-Math-Calc-Units perl-Config-Tiny perl-Parse-RecDescent




systemctl


./traf_tools_setup.sh -d /workspaces/.common/download_software_tools -i /workspaces/.common/installed_software_tools

sudo ln -s /usr/bin/python3 /usr/bin/python
sudo ln -s /usr/lib64/libsnappy.so.1 /usr/lib64/libsnappy.so

  rm $TRAF_VAR/ms.env
  sqgen
  sqstart

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/workspaces/.common/installed_software_tools/protobuf-2.5.0/lib/
export LIBRARY_PATH=$LIBRARY_PATH:/workspaces/.common/installed_software_tools/protobuf-2.5.0/lib/
export PATH=$PATH:/workspaces/.common/installed_software_tools/protobuf-2.5.0/bin/
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/workspaces/.common/installed_software_tools/protobuf-2.5.0/include/
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/workspaces/.common/installed_software_tools/protobuf-2.5.0/include/
export PKG_CONFIG_PATH=/workspaces/.common/installed_software_tools/protobuf-2.5.0/lib/pkgconfig/